In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
a = np.array([10,    45,  45,  85,   75,   96,     84653])

In [5]:
a

array([   10,    45,    45,    85,    75,    96, 84653])

In [6]:
type(a)

numpy.ndarray

In [7]:
a1 = np.array([45,85,'74','32','4156','15361','python','java'])

In [8]:
a1

array(['45', '85', '74', '32', '4156', '15361', 'python', 'java'],
      dtype='<U11')

In [9]:
# int---float---str

In [10]:
a3 = np.array([54,541,546,32,3615],dtype ='float')

In [11]:
a3

array([  54.,  541.,  546.,   32., 3615.])

In [12]:
a3 = np.array([54,541,546,32,3615],dtype ='str')

In [13]:
a3

array(['54', '541', '546', '32', '3615'], dtype='<U4')

In [14]:
a4 = [10,20,30]

In [15]:
import numpy as np

In [16]:
x1 = [88,45,45,75,36]

In [17]:
x2 = np.array([87,55,663,77,12,54,'python'])

In [18]:
x2

array(['87', '55', '663', '77', '12', '54', 'python'], dtype='<U11')

In [19]:
x2.itemsize

44

In [20]:
x1

[88, 45, 45, 75, 36]

In [21]:
x2 = np.array([87,55,63,77,12,54],dtype='int8')

In [22]:
x2

array([87, 55, 63, 77, 12, 54], dtype=int8)

In [23]:
x2.itemsize

1

In [24]:
len(x2)*x2.itemsize


6

In [25]:
x1

[88, 45, 45, 75, 36]

In [26]:
import sys

In [27]:
sys.getsizeof(x1[0])*len(x1)

140

In [32]:
import time
start_time = time.time()
p = [ i for i in range(8787421)]
end_time = time.time()
print("total time by list:",end_time-start_time)

total time by list: 0.5199346542358398


In [31]:
start_time = time.time()
p = [ i for i in np.arange(8787421)]
end_time=time.time()
print("total time by np array",end_time-start_time)

total time by np array 0.6374273300170898


In [33]:
import numpy as np

In [35]:
a = np.array([85,77,96,336])

In [36]:
a.ndim

1

In [38]:
a = np.array([[87,55,66,33,22],[87,55,69,78,32]])

In [40]:
a.ndim

2

In [45]:
a = np.array([[78,85,96,78],[77,55,66,85],[74,85,74,986],[45,74,36,25]])

In [46]:
a.ndim

2

In [60]:
a1 = np.array([[[1,2,3,4],[4,8,5,7]],[[10,20,30,40],[85,74,96,88]],[[85,74,96,33],[45,89,74,52]]])

In [61]:
a1

array([[[ 1,  2,  3,  4],
        [ 4,  8,  5,  7]],

       [[10, 20, 30, 40],
        [85, 74, 96, 88]],

       [[85, 74, 96, 33],
        [45, 89, 74, 52]]])

In [63]:
a1.ndim

3

In [2]:
import numpy as np

In [13]:
a2 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[1,2,3]],[[88,88,96],[15,25,36]],[[25,44,58],[84,52,41]]
              ])

In [14]:
a2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 4,  5,  6],
        [ 1,  2,  3]],

       [[88, 88, 96],
        [15, 25, 36]],

       [[25, 44, 58],
        [84, 52, 41]]])

In [15]:
a2.ndim

3

In [ ]:

import numpy as np
import time
starttime=time.time()


In [ ]:
a = np.array(23,85,74,96,45,2563,65)

In [ ]:
a.ndim

In [ ]:
a = np.array([[1,2,3,4],[100,200,300,400]])

In [ ]:
a

In [ ]:
a.ndim

In [ ]:
a = np.ones((4,4))

In [ ]:
a

In [ ]:
np.linspace(10,20,4)